# Generated by Django 4.2.23 on 2025-06-29 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qr_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="qrcodesession",
            options={
                "verbose_name": "QR Code Session",
                "verbose_name_plural": "QR Code Sessions",
            },
        ),
    ]
